//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RTA_Transit_Feedback
{
    using System;
    using System.Collections.Generic;
    
    public partial class FeedBackForm
    {
        public int FeedbackID { get; set; }
        public string FeedbackDescription { get; set; }
        public System.DateTime DateofRide { get; set; }
        public Nullable<System.TimeSpan> TimeofRide { get; set; }
        public string RouteName { get; set; }
        public string VehNum { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<int> BatchID { get; set; }
    
        public virtual Batch Batch { get; set; }
        public virtual Customers Customers { get; set; }
    }
}
